MultiLevel Reseller Detection Fix and Update
CpanelInc/SSP pull request #10
Opened 2017-06-10 06:31 UTC by cPanelRicky

Fixes [TICKETS-1424] - Zamfoo detection no longer works

- Change Zamfoo plugin check to look for plugin directory rather than checking for the word Zamfoo in /scripts/prekillacct
- Consolidate all Multilevel reseller plugin checks into a single check
- Update version to 4.99.156

2017-06-10 12:15 UTC, cPanelChrisD approved these changes
Looks good!

2017-06-14 19:26 UTC, davelcpanelnet-zz requested changes
There are some minor changes I would like toe here.
- Array Definition
- Variable name

2017-06-14 19:26 UTC, davelcpanelnet commented on ssp
> +    my @ml_plugins = ( 'zamfoo', 'whmreseller', 'whmphp', 'whmamp' );
I would like to see some clearer standardized array creation when it's static like this. qw() is really the preferred best practice.

EX:
```
• [root@davel:/usr/local/cpanel] (hb_integration_66)# /usr/local/cpanel/3rdparty/bin/perl -MData::Dumper -e 'my @ml_plugins = qw/ zamfoo whmreseller whmphp whmamp /; print Dumper \@ml_plugins'
$VAR1 = [
          'zamfoo',
          'whmreseller',
          'whmphp',
          'whmamp'
        ];
```
This isn't something I am going to reject - but it's best practice.

2017-06-14 19:26 UTC, davelcpanelnet commented on ssp
> +    my $docroot = '/usr/local/cpanel/whostmgr/docroot/cgi';
I'd like a different variable name here.  $docroot implies an absolute root RE: Apache so that's a bit misleading.

2017-06-14 19:26 UTC, davelcpanelnet commented on ssp
> +    my $docroot = '/usr/local/cpanel/whostmgr/docroot/cgi';
$cgi_root would work

2017-06-14 19:26 UTC, davelcpanelnet commented on ssp
> +            print_3rdp2('is installed. Multi-level reseller setups are not supported!');
Please remove the exclamation

2017-06-14 19:26 UTC, closed without merging

2017-06-14 23:09 UTC, cPanelRicky commented
Instead of closing these when minor changes are needed, if you leave the pull request open the subsequent commits to the branch will automatically be reflected in the pull request removing the need to open a whole new one.

2017-06-14 23:26 UTC, davelcpanelnet commented
I will take that into consideration 

Sent from my iPhone

> On Jun 14, 2017, at 6:09 PM, Ricky Grassmuck <notifications@github.com> wrote:
> 
> Instead of closing these when minor changes are needed, if you leave the pull request open the subsequent commits to the branch will automatically be reflected in the pull request removing the need to open a whole new one.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
>