Check PassiveIP eq External IP, Eximstats to M-M-M-Monster Logs, /var/cpanel/tomcat.options -Xss2m
CpanelInc/SSP pull request #15
Opened 2017-07-21 04:07 UTC by cPPietila

3 commits to alter the functionality of SSP.

- Ignore -Xss2m in /var/cpanel/tomcat.options
- Add eximstats_db.sqlite3 to M-M-M-MONSTER LOG
- Add checking that FTP announces correct IP

2017-07-21 12:35 UTC, cPanelChrisD requested changes
Please create and assign JIRA TECH cases to yourself for each issue that you will be addressing in SSP.  For example, you can assign TECH-296 to yourself and mark it as completed (with a link to the matching commit in your personal fork of the repo, please).

This is also going to conflict with the pull request I sent in yesterday.  That merge will additionally begin the requirement that SSP passes perlcritic tests defined in the Makefile with the provided perlcritic profile, in addition to being tidy.  After that pull is merged, you can "make test" to just run the tests, and "make tidy" will run both test and tidy targets.

2017-07-21 12:35 UTC, cPanelChrisD commented on ssp
> +            if ( defined( $CPCONF{'ftpserver'} ) ) {
These if blocks should be combined:
if ( defined( $CPCONF{'ftpserver'} ) and ( $passiveip ne $EXTERNAL_IP_ADDRESS ) ) {

2017-07-21 12:35 UTC, cPanelChrisD commented on ssp
> +                    $passiveiptext = "MasqueradeAddress ( " . $passiveip . " ) doesn't match license IP";
Concatenate this text on the end of $passivetext, it's not necessary to put it in a separate $passiveiptext.  6 lines of code can be dropped by doing so, reducing complexity.

2017-07-21 14:16 UTC, davelcpanelnet commented on ssp
> +            if ( defined( $CPCONF{'ftpserver'} ) ) {
You probably want to enforce the logic here even further as well:
```
if ( exists $passiveip && $passiveip ne $EXTERNAL_IP_ADDRESS && defined( $CPCONF{'ftpserver'} )
```

2017-07-21 14:18 UTC, davelcpanelnet commented
Please make the changes requested and be sure to note the TECH-* for proper visibility.

This pull request will be left open so please feel free to make those updates and even make a few changes should you wish.

2017-07-22 22:20 UTC, cPPietila commented
I've gone ahead and made the requested changes.

2017-07-25 12:34 UTC, cPanelChrisD approved these changes
All looks good.  Ready for Dave's review.

2017-07-25 16:55 UTC, davelcpanelnet commented
Good to go.

2017-07-25 16:55 UTC, merged