[TECH-540] Add Puppet and SaltStack config management software detection
CpanelInc/SSP pull request #55
Opened 2018-05-07 14:36 UTC by youvegotmoxie

This change allows SSP to detect if Puppet or SaltStack is running on a host.

2018-05-07 15:26 UTC, davelcpanelnet-zz requested changes
Please make the requested version bump and we should be good to go!

2018-05-07 15:26 UTC, davelcpanelnet commented on ssp
> +our $VERSION = '4.99.187';
187 was just merged in prior to this commit so this will need to be changed to '4.99.188'

@cPanelChrisD came in for the kill /w \.187 heheh.

2018-05-07 15:26 UTC, davelcpanelnet commented on ssp
> +    return unless exists_process_cmd( qr{ salt-minion }xms, 'root' );
I like this return structure.

2018-05-07 15:28 UTC, davelcpanelnet commented
@youvegotmoxie small improvement is making the commits more tangible as well.

As they look now they are pretty rough.  It's something I do too and kinda have to force my own refinement.

You can always, once you are done, circle back and squash things into place.

2018-05-07 15:37 UTC, youvegotmoxie commented
Bumped the version again.

2018-05-07 16:17 UTC, youvegotmoxie commented
Squashing the commits is something I'll have to play around with, I attempted to do it after the fact but it doesn't appear to have made any difference in the commit history shown in the merge request.

2018-05-07 16:27 UTC, troglodyne commented
You'll have to push with --force if you squash the commits, as intentionally altering your commit history (like with squashed commits) requires this. That's probably why the branch on the github remote probably doesn't appear to have been updated.

2018-05-07 16:41 UTC, youvegotmoxie commented
That worked great, thanks Andy.

2018-05-07 18:19 UTC, davelcpanelnet-zz approved these changes
Looks good!

2018-05-07 18:19 UTC, davelcpanelnet-zz commented on ssp
> +our $VERSION = '4.99.188';
Awesome. **cleanly done**

2018-05-07 18:27 UTC, merged

2018-05-08 13:11 UTC, cPanelChrisD commented
Right on, this is perfect.  I belatedly approve. 👍